version: "3.7"
services:
  app-mysqldb:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=mysql
    ports:
      - "3306:3306"

  app:
    build: .
    restart: always
    container_name: app-backend
    ports:
      - "8888:8888"
    depends_on:
      - app-mysqldb
    environment:
      - DATABASE_HOST=app-mysqldb
      - DATABASE_USER=root
      - DATABASE_PASSWORD=mysql
      - DATABASE_NAME=root
      - DATABASE_PORT=3306
      - SPRING_DATASOURCE_URL=jdbc:mysql://app-mysqldb:3306/mysql?autoReconnect=false&useSSL=false&allowPublicKeyRetrieval=true